#%RAML 1.0
title: american_flight_sapi
/flight:
  get:
    queryParameters:
      destination:
        required: false
        enum:
          - LAX
          - SFO
          - CLE
    headers:
      client_id:
        required: false
      client_secrect: 
        required: false
    responses: 
      200:
        body:
          application/json:
            examples: 
              value: 
                -
                  ID: 1
                  code: Er38
                  price: 400
                  departureDate: 2023/10/17
                  origin: CLE
                  destination: SFO
                  emptyseats: 30
                  plane: 
                    type: Boeing 333
                    totalseats: 400

                ID: 2
                code: EP46
                price: 600
                departureDate: 2023/10/27
                origin: CLE
                destination: LAX
                emptyseats: 20
                plane:
                  type: Boeing 444
                  totalseats: 300
                  
              


    
  post:
  /{ID}:
    get:
    delete:
    put:
    patch:
      