#%RAML 1.0
title: american_flight_sapi
types:
  AmericanFlight: !include /dataType/americanFlightDataType.raml
uses:
  security: /Library/AFlibrary.raml 
  
/flight:
  is: [security.client_Id_enforcement]
  get:
    queryParameters:
      destination:
        required: false
        enum:
          - LAX
          - SFO
          - CLE

    responses: 
      200:
        body:
          application/json: 
            type: AmericanFlight[]
            examples: !include /Examples/americanFlightsexample.raml
              
                
  post:
    
    body:
      application/json:
          type: AmericanFlight
          example: !include /Examples/americanFlightPostIDexample.raml
    responses:
      201:
        body:
          application/json:
            example: 
              message: Flight added successfully 
              
        

  /{ID}:
    is: [security.client_Id_enforcement]
    get:
      responses:
        200:
          body:
            application/json:
              
    delete:
      responses:
        200:
          body:
            application/json:
              example:
                message: flight deleted successfully 
    put:
    patch:
      