#%RAML 1.0
title: american_flight_sapi
/flight:
  get:
    queryParameters:
      destination:
        required: false
        enum:
          - LAX
          - SFO
          - CLE
    headers:
      client_id:
        required: false
      client_secrect: 
      


    
  post:
  /{ID}:
    get:
    delete:
    put:
    patch:
      