#%RAML 1.0 DataType
type: object
properties:
  ID: 
    type: integer
  code: 
    type: string
  price: 
    type: number
  departureDate: 
    type: string
  origin: 
    type: string
  destination: SFO
  emptyseats: 30
  plane: 
    type: Boeing 333
    totalseats: 400