#%RAML 1.0 DataType
type: object
properties:
  ID: 
    type: integer
  code: 
    type: 
  price: 400
  departureDate: 2023/10/17
  origin: CLE
  destination: SFO
  emptyseats: 30
  plane: 
    type: Boeing 333
    totalseats: 400